---
- name: Deploy Reactjs Playbook 
  hosts: 
    - worker02
  vars: 
    image_name: "69966/reactjs-jenkins-nginx:v1.0.0"
  tasks: 
    - name: Install Docker  
      apt: 
        name: docker 
        state: present 
    - name: Install docker compose 
      apt: 
        name: docker-compose 
        state: present 
    - name: Add current user into docker group 
      user: 
        name: keo # variables for the current user 
        groups: 
          - docker 
        append: true
    - name: Start Reactjs with docker compose
      docker_compose: 
        project_name: reactjs-new-srv
        definition:
          services:
            reactjs_srv:   
              image: {{ image_name }}
              container_name: reactjs-new-cont
              ports: 
                - "3000:80"
    - name: Adding domain for the website 
      debug: 
        msg: "Domain name is not yet ready!!"